config/routes.rb
UrailsRumble::Application.routes.draw do
  

  match "/rules" => "pages#rules", via: :get
  match "/teams/mailer" => "teams#mailer"

  resources :teams, only: [:show, :index, :new, :create, :update] do
    get :join, on: :collection
    get :leave, on: :collection
  end

  root :to => "pledges#index"

  resources :pledges, only: [:create]
  
  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'
  match "/signout" => "authentications#destroy", :as => :signout

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

  validates :email, :presence => true, 
                    :uniqueness => true,
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
  attr_accessible :name, :password, :bit_bucket, :heroku
  
  validates :name, :uniqueness => true
  validates :name, :password, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :team
  attr_accessible :name, :provider, :team_id, :uid, :email

  validates :uid, :uniqueness => true
  validates :provider, :presence => true
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
      user.email = auth["info"]["email"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :valid_email?

  def authenticate!
   	redirect_to root_path and return if current_user.nil?
  end

  private

    def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def valid_email?(email)      
      if email =~ /^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/
        return true
      else
        return false
      end
    end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    #redirect_to root_url, :notice => "Signed in!"
    redirect_to new_team_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def rules
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def index
    redirect_to current_user.team if current_user && current_user.team
    @pledge = Pledge.new
  end

  def create
    @pledge = Pledge.create(params[:pledge])

    if @pledge.save
      flash[:success] = "Thanks! We'll keep you posted."
      redirect_to root_path
    else
      render :index
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ActionController::Base
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  before_filter :authenticate!, only: [:new, :create, :show, :join]
  before_filter :forward_if_has_team, only: [:new]
  before_filter :authenticate_current_user!, only: [:show, :update]

  def index
    @teams = Team.all
  end

  def create
    # Hoa
    @team = Team.create(params[:team])
    @user = current_user
   
    if @team.save
         @user.update_attributes(:team_id => @team.id)
         flash[:notice] = "Successfully created Team."
         redirect_to team_path(@team)
    else
        @teams = Team.all
         flash[:alert] = "There was an error in creating your team."
         render :action => 'new'
       end
   
  end

  def new
    # redirect_to root_path if current_user.nil?
    # Hoa
    @teams = Team.all
    @team = Team.new
    
  end

  def join
    @team = Team.find(params[:team][:id])

    if @team.password != params[:team][:password]
      flash[:error] = "Incorrect password"
      redirect_to new_team_path and return
    end

    if @team.users.size >= 4
      flash[:error] = "The team you selected is full."
      redirect_to new_team_path and return
    end

    @team.users << current_user

    redirect_to team_path(@team)
  end

  def leave
    current_user.team = nil
    current_user.save
    redirect_to new_team_path
  end

  def show
    @team = Team.find(params[:id])
    @user = current_user

    # Landon
  end

  def update
    # need if statement here because Send Invite is inside team form
    if params[:commit] == "Send Invite"
      mailer
    else
      @team = Team.find(params[:id])
      @team.update_attributes(team_params)
      @team.save!
      redirect_to team_path(@team)
    end
  end

  def mailer
    email = params[:email]
    team = Team.find(params[:team_id])
    if valid_email?(email)
      TeamMailer.send_invite(email, team).deliver
      flash[:success] = "Invite has been sent"
      redirect_to :back
    else
      flash[:failure] = "The email address you entered is not valid"
      redirect_to :back
    end
  end

  private
    def forward_if_has_team
       redirect_to team_path(current_user.team) and return if current_user && current_user.team
    end    
    def team_params
      params[:team].slice :name, :password, :heroku, :bit_bucket
    end

    def authenticate_current_user!
      @team = Team.find(params[:id])
      redirect_to root_path and return unless @team.users.include?(current_user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pledge_helper.rb
module PledgeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/authentications/index.html.erb
<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
  </tr>
  <% for authentication in @authentications %>
    <tr>
      <td><%= authentication.user_id %></td>
      <td><%= authentication.provider %></td>
      <td><%= authentication.uid %></td>
      <td><%= link_to "Destroy", authentication, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/_favicon.html.erb
<%# We don't have a favicon yet. %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_nav.html.haml
-# %li= link_to "Teams", teams_path
%li= link_to "Rules", rules_path
- if current_user
  - if current_user.team
    %li= link_to "My Team", current_user.team
  - else
    %li= link_to "Create or Join a Team", new_team_path
  %li= link_to "Sign out", signout_path, method: :delete
- else
  %li= link_to "Sign in with GitHub", "/auth/github"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "URails Rumble" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%# Add this back when we have a favicon %>
    <%# render "layouts/favicon" %>

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">URails Rumble</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <%= render "layouts/nav" %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-content">
        <div class="row">
          <div class="span12">
			<% flash.each do |name, msg| %>
			  <% if msg.is_a?(String) %>
			    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
			      <a class="close" data-dismiss="alert">&#215;</a>
			      <%= content_tag :div, msg, :id => "flash_#{name}" %>
			    </div>
			  <% end %>
			<% end %>
             <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/rules.html.haml
.rules
  %h1 Rumble Rules
  %br/
  %br/
  %h2 Basics
  %p Teams of 1 - 4 will compete to create a website in 48 hours. Teams are not assigned, you may choose your own team. All teams must register with the website (when registrations are open) in order to be eligible for the competition.
  %h2 When and Where
  %p Registration, where compeitors can to assemble their teams through the website, will begin near the end of November. <strong>The competition itself will begin at 12PM (noon) on Dec 18th and end at 12PM on Dec 20th.</strong> We will have L130 reserved for your team to work in if you need to, however this is not required. You may pick a room at the top of Warnock, work remotely, whatever you like. There will be a few meals provide by 12 Spokes, a local Ruby shop that graciously decided to sponsor this event!
  %h2 Logistics
  %p There are 3 parts to the competition with the following date ranges:
  %ul 
    %li 
      %strong Registration 
      \- End of November - Dec 17th
    %li 
      %strong Competition 
      \- Dec 18th - Dec 20th
    %li 
      %strong Judging 
      \- Dec 20th - Dec 21st
  %h4 Registration
  %p Everything is free.
  %p In order to register with the website, you will have to have a #{ link_to "GitHub account", "https://github.com/" }.
  %p Every team will be required to use Git for version control, and #{ link_to "BitBucket", "http://bitbucket.com" } to host their project. BitBucket gives free private repositories for teams of up to 5 members.
  %p If you are unfamiliar with Git, you can #{ link_to "try it out here", "http://try.github.com/" }.
  %p You will be required to add the URailsRumble user as a collaborator on your BitBucket repository. Only approved moderators will have access to the URailsRumble account, which will be used to ensure no cheating is going on. As soon as the judging portion is finished, you may remove the URailsRumble user. We will not abuse our access to your repository and everything you build is completely yours.
  %p You will host your app on Heroku. Before the competition begins, you must register your __________.herokuapp.com URL with the website. If you are unfamiliar with Heroku, #{ link_to "here's a great getting started guide" }.
  %p We highly recommend you become familiar with Git, Heroku, and BitBucket well before the compeition begins. You can create your Heroku app and your BitBucket repository well in advance, no need to wait until the competition begins. We will give you a nice checklist of things that need to be done once registration begins, so no need to fret too much over it now.
  %h4 Competition
  %p You and your team will have 48 hours to complete your website, from 12PM on Dec. 18th to 12PM on Dec. 20th. We will be periodically monitoring repositories for suspicious activity, so make sure you commit often and not everything all at once. See below for what you are allowed to do during vs. before the competition.
  %h4 Judging
  %p Judging will begin as soon as the competition ends on December 20th, with winners announced and awarded sometime on December 21st or 22nd. We will notify all winners via email and post the results on the front page of this site. 
  %p We've hand-picked some fantastic judges, all of which are prominent members of the web/app community in Utah:
  %ul
    %li
      = link_to "Clifton Labrum", "http://twitter.com/cliftonite" 
      \- A local web and app designer, most notably 
      = link_to "Pilot Pro", "http://pilotpro.com"
    %li 
      = link_to "Zach Holmquist", "http://twitter.com/zholmquist" 
      \- A local web and app developer, most notably 
      = link_to "Track 8", "http://track8.fm"
    %li TBA
  %p Judges will each of the following categories a score of 1 - 10 in the following categories. Those with the highest scores will win. The judges will be asking themselves these questions about your app:
  %ul
    %li
      %strong UI/Design
      \- How appealing/attractive is your visual and graphic design? Is it appropriate as it relates to your app idea?
    %li
      %strong User Experience (UX)
      \- Is your app pleasant to use? From the landing page, do I know immediately what your app does and how to use it?
    %li
      %strong Concept/Idea
      \- Is your app idea unique? Does it solve a common problem in a new/better way?
    %li 
      %strong Difficulty
      \- Given a 48 hour time constraint, how difficult was your idea to implement and how well did you implement it?
  %h2 What are you allowed to do before the competition?
  %p You are allowed to do pretty much anything you want <em>except</em>:
  %ul
    %li Write code specific to your app.
    %li Design any graphics or images for your site.
  %p You also may not wrap the core functionality of your app in a gem, for example. You may write any general purpose libraries, freely distributed as a gem, as long as it is generally useful outside of your app domain.
  %p We recommend you do the following before the competition begins:
  %ul
    %li Decide on an idea/concept.
    %li Decide on a name, reserve any domain names if necessary.
    %li Brainstorm features.
    %li Wireframe the app and create flow charts.
  %p As long as you are not creating any assets (images/graphic design) or code specific to your app, you are probably allowed to do it. Feel free to #{ mail_to "urailsrumble@gmail.com", "contact the admins at urailsrumble@gmail.com" } if you have any questions.
  %h2 What now?
  %p Enter your email on the main page, and you will receive an email when registrations are ready to begin!

app/views/pledges/index.html.erb
<h1 class="rumble">URails Rumble!</h1>

<p>
A competition for Ruby on Rails developers and designers. Groups of 1 - 4 have 48 hours to build an awesome website, from Dec 18th - Dec 20th. The vivid details are on the <%= link_to "rules page", rules_path %>. Sign in and create your team to get started!</p>

<br />
<div style="text-align:center;">
<%= link_to "Sign in with Github", "/auth/github", class: "btn btn-large btn-custom" %>
</div>

<% if @pledge.errors.present? %>
  <div style="text-align:center;">
    <ul class="errors">
    <% @pledge.errors.full_messages.each do |mess| %>
      <li><%= mess %></li>  
    <% end %>
    </ul>
  </div>
<% end %>

<% if flash[:success] %>
  <div class="success"><%= flash[:success] %></div>
<% end %>
<div class="clear"></div>